export const safelistIcons = [
  // list & view
  'i-mdi-format-list-text',
  'i-mdi-format-list-numbered',
  'i-mdi-format-list-bulleted',
  'i-mdi-format-align-justify',
  'i-mdi-format-align-left',
  'i-mdi-format-align-center',
  'i-mdi-format-align-right',
  'i-mdi-format-align-top',
  'i-mdi-format-align-middle',
  'i-mdi-format-align-bottom',
  'i-mdi-format-line-style',
  'i-mdi-order-alphabetical-ascending',
  'i-mdi-order-bool-ascending',
  'i-mdi-order-bool-ascending-variant',
  'i-mdi-order-numeric-ascending',
  'i-mdi-view-agenda',
  'i-mdi-view-array',
  'i-mdi-view-carousel',
  'i-mdi-view-column',
  'i-mdi-view-comfy',
  'i-mdi-view-compact',
  'i-mdi-view-dashboard',
  'i-mdi-view-grid',
  'i-mdi-view-quilt',
  'i-mdi-view-sequential',
  'i-mdi-form-select',
  'i-mdi-table-large',
  'i-mdi-format-text',
  'i-mdi-format-letter-case',

  // form
  'i-mdi-pencil',
  'i-mdi-magnify',
  'i-mdi-content-save-outline',
  'i-mdi-trash-can-outline',
  'i-mdi-numeric',
  'i-mdi-radiobox-marked',
  'i-mdi-checkbox-marked-outline',
  'i-mdi-content-cut',
  'i-mdi-content-copy',
  'i-mdi-content-paste',
  'i-mdi-cached',
  'i-mdi-reload',
  'i-mdi-reply',
  'i-mdi-cog-outline',

  // account
  'i-mdi-account',
  'i-mdi-account-multiple',
  'i-mdi-account-edit',
  'i-mdi-account-search',
  'i-mdi-account-check',
  'i-mdi-account-cancel',
  'i-mdi-account-settings-variant',
  'i-mdi-shield-outline',
  'i-mdi-shield-check-outline',
  'i-mdi-shield-lock-outline',

  // chart
  'i-mdi-chart-line',
  'i-mdi-chart-areaspline-variant',
  'i-mdi-chart-bar',
  'i-mdi-chart-bar-stacked',
  'i-mdi-chart-bell-curve',
  'i-mdi-chart-bell-curve-cumulative',
  'i-mdi-chart-pie-outline',
  'i-mdi-gauge',
  'i-mdi-chart-timeline',
  'i-mdi-chart-waterfall',
  'i-mdi-finance',

  // file
  'i-mdi-file-outline',
  'i-mdi-file-account-outline',
  'i-mdi-file-chart-outline',
  'i-mdi-file-code-outline',
  'i-mdi-file-upload-outline',
  'i-mdi-file-download-outline',
  'i-mdi-file-edit-outline',
  'i-mdi-file-image-outline',
  'i-mdi-file-search-outline',
  'i-mdi-file-table-outline',
  'i-mdi-file-word-box-outline',
  'i-mdi-file-excel-box-outline',
  'i-mdi-file-pdf-box-outline',
  'i-mdi-image-outline',
  'i-mdi-image-marker-outline',
  'i-mdi-clipboard-list-outline',
  'i-mdi-clipboard-file-outline',

  'i-mdi-folder-outline',
  'i-mdi-folder-cog-outline',
  'i-mdi-folder-marker-outline',
  'i-mdi-folder-pound-outline',
  'i-mdi-folder-star-outline',
  'i-mdi-folder-upload-outline',
  'i-mdi-folder-download-outline',
  'i-mdi-folder-wrench-outline',
  'i-mdi-folder-network-outline',

  // bell & alert
  'i-mdi-alarm',
  'i-mdi-bell-outline',
  'i-mdi-bell-off-outline',
  'i-mdi-bell-ring-outline',
  'i-mdi-bell-alert-outline',
  'i-mdi-bell-badge-outline',
  'i-mdi-alarm-light-outline',
  'i-mdi-alarm-light-off-outline',
  'i-mdi-alert-outline',
  'i-mdi-alert-circle-outline',

  // shape
  'i-mdi-star',
  'i-mdi-star-outline',
  'i-mdi-star-check',
  'i-mdi-star-plus',
  'i-mdi-star-remove',
  'i-mdi-eye',
  'i-mdi-heart',
  'i-mdi-heart-outline',
  'i-mdi-trophy',
  'i-mdi-thumb-up',
  'i-mdi-vector-line',
  'i-mdi-vector-triangle',
  'i-mdi-vector-square',
  'i-mdi-rhombus-outline',
  'i-mdi-pentagon-outline',
  'i-mdi-cube-outline',
  'i-mdi-cylinder',
  'i-mdi-vector-arrange-below',
  'i-mdi-vector-combine',
  'i-mdi-arrange-bring-forward',
  'i-mdi-arrange-send-backward',
  'i-mdi-vector-point-select',
  'i-mdi-rhombus-split',
  'i-mdi-shape',
  'i-mdi-shape-plus',
  'i-mdi-source-branch',
  'i-mdi-source-fork',
  'i-mdi-source-merge',
  'i-mdi-graph',

  // arrow
  'i-mdi-arrow-left',
  'i-mdi-arrow-right',
  'i-mdi-arrow-up',
  'i-mdi-arrow-down',
  'i-mdi-chevron-double-left',
  'i-mdi-chevron-double-right',
  'i-mdi-chevron-double-up',
  'i-mdi-chevron-double-down',
  'i-mdi-arrow-left-bold-box-outline',
  'i-mdi-arrow-right-bold-box-outline',
  'i-mdi-arrow-up-bold-box-outline',
  'i-mdi-arrow-down-bold-box-outline',
  'i-mdi-arrow-expand-horizontal',
  'i-mdi-arrow-expand-vertical',
  'i-mdi-tray-arrow-up',
  'i-mdi-tray-arrow-down',
  'i-mdi-arrow-expand-all',
  'i-mdi-arrow-collapse-all',
  'i-mdi-arrow-decision',

  // tooltip
  'i-mdi-tooltip-outline',
  'i-mdi-tooltip-text-outline',
  'i-mdi-tooltip-edit-outline',
  'i-mdi-tooltip-check-outline',
  'i-mdi-information-box-outline',
  'i-mdi-information-outline',

  // calendar
  'i-mdi-clock-outline',
  'i-mdi-hours-12',
  'i-mdi-hours-24',
  'i-mdi-calendar',
  'i-mdi-calendar-text-outline',
  'i-mdi-calendar-clock',
  'i-mdi-calendar-month',
  'i-mdi-calendar-multiselect',
  'i-mdi-update',

  // cloud
  'i-mdi-cloud',
  'i-mdi-cloud-outline',
  'i-mdi-cloud-upload-outline',
  'i-mdi-cloud-download-outline',
  'i-mdi-cloud-check-variant-outline',
  'i-mdi-cloud-alert-outline',
  'i-mdi-cloud-refresh-variant-outline',
  'i-mdi-cloud-search-outline',

  // database
  'i-mdi-database',
  'i-mdi-database-outline',
  'i-mdi-database-arrow-up',
  'i-mdi-database-arrow-down',
  'i-mdi-database-clock',
  'i-mdi-database-cog',
  'i-mdi-database-edit',
  'i-mdi-database-eye',
  'i-mdi-database-lock',
  'i-mdi-database-refresh',
  'i-mdi-database-search',
  'i-mdi-database-sync',

  // device & tech
  'i-mdi-phone',
  'i-mdi-phone-classic',
  'i-mdi-cellphone',
  'i-mdi-tablet',
  'i-mdi-laptop',
  'i-mdi-monitor',
  'i-mdi-monitor-dashboard',
  'i-mdi-desktop-tower',
  'i-mdi-disc-player',
  'i-mdi-printer',
  'i-mdi-earbuds',
  'i-mdi-headphones',
  'i-mdi-camera',
  'i-mdi-camera-iris',
  'i-mdi-microphone',
  'i-mdi-volume-low',
  'i-mdi-volume-medium',
  'i-mdi-volume-high',
  'i-mdi-video-outline',
  'i-mdi-video-off-outline',
  'i-mdi-video-wireless-outline',
  'i-mdi-video-2d',
  'i-mdi-video-3d',
  'i-mdi-cctv',
  'i-mdi-hdmi-port',
  'i-mdi-battery-50',
  'i-mdi-battery-charging-50',
  'i-mdi-battery-charging-wireless-50',
  'i-mdi-router-wireless',
  'i-mdi-server',
  'i-mdi-cast',
  'i-mdi-link',
  'i-mdi-bluetooth',
  'i-mdi-access-point-network',
  'i-mdi-signal-cellular-3',
  'i-mdi-wifi',
  'i-mdi-lan',
  'i-mdi-web',

  // building & environment
  'i-mdi-electric-switch',
  'i-mdi-power',
  'i-mdi-power-plug',
  'i-mdi-engine',
  'i-mdi-robot-industrial',
  'i-mdi-transmission-tower',
  'i-mdi-factory',
  'i-mdi-hydro-power',
  'i-mdi-solar-panel',
  'i-mdi-solar-power',
  'i-mdi-solar-power-variant',
  'i-mdi-wind-power',
  'i-mdi-wind-turbine',
  'i-mdi-fire',
  'i-mdi-water',
  'i-mdi-snowflake',
  'i-mdi-leaf',
  'i-mdi-flower-tulip',
  'i-mdi-tree',
  'i-mdi-pine-tree',
  'i-mdi-forest',
  'i-mdi-thermometer',
  'i-mdi-thermometer-water',
  'i-mdi-thermometer-lines',
  'i-mdi-fan',
  'i-mdi-lightbulb',

  // navigation
  'i-mdi-navigation',
  'i-mdi-map-marker',
  'i-mdi-map-marker-path',
  'i-mdi-map-outline',
  'i-mdi-map-search-outline',
  'i-mdi-crosshairs-gps',
  'i-mdi-compass-outline',
  'i-mdi-earth',
  'i-mdi-earth-box',
  'i-mdi-bicycle',
  'i-mdi-atv',
  'i-mdi-truck',
  'i-mdi-car',
  'i-mdi-bus',
  'i-mdi-train',
  'i-mdi-subway-variant',
  'i-mdi-ferry',
  'i-mdi-airplane',
  'i-mdi-airplane-landing',
  'i-mdi-airplane-takeoff',
  'i-mdi-airport',
  'i-mdi-rocket-launch',
  'i-mdi-traffic-light',
  'i-mdi-highway',

  // other
  'i-mdi-home',
  'i-mdi-home-edit',
  'i-mdi-home-search',
  'i-mdi-bed',
  'i-mdi-store',
  'i-mdi-storefront-outline',
  'i-mdi-cart',
  'i-mdi-silverware-variant',
  'i-mdi-flask',
  'i-mdi-gamepad',
  'i-mdi-shopping-outline',
  'i-mdi-gift-outline',
  'i-mdi-timer-outline',
  'i-mdi-timer-sand-complete',
  'i-mdi-balloon',
  'i-mdi-emoticon',
  'i-mdi-emoticon-excited',
  'i-mdi-emoticon-neutral',
  'i-mdi-emoticon-frown',
  'i-mdi-emoticon-cry',
  'i-mdi-music',
  'i-mdi-music-circle-outline',
  'i-mdi-music-clef-treble',
  'i-mdi-palette-outline',
  'i-mdi-application-braces-outline',
  'i-mdi-code-block-braces',
  'i-mdi-language-javascript',
  'i-mdi-language-typescript',
  'i-mdi-api',
  'i-mdi-hammer',
  'i-mdi-sickle',
];
